elfloader: cast linker symbol to avoid warining
The _end symbol is declared as char[]. Newer compilers raise warnings
about array out of bounds access here:
error: array subscript -1 is outside array bounds of ‘char[]’ [-Werror=array-bounds]